# GUI中保存的日志设置
auto_scroll: True

# GUI中保存的自定义舰船名称
custom_ss_names:
  - "决战1"
  - "决战10"
  - "决战2"
  - "决战3"
  - "决战4"
  - "决战5"
  - "决战6"
  - "决战7"
  - "决战8"
  - "决战9"
sortie_times: 1

# GUI中保存的活动设置
event_automation:
  event_folder: '20250710'
  plan_name: E9A夜战
  fleet_id: 1
  battle_count: 100
  reuse_daily_settings: True
  bonus_check_interval: 1800
